### ISSUE TITLE
Calculator calculates sums wrongs and triggers NaN animation

### ISSUE THREAD

**Issue by mcky** [os-js/OS.js#455]
## Expected behaviour
When inputting the sum `55*5-9` the result should be `266`

## Actual behaviour
The calculator performs a spinning animation and returns `9-` 

## Steps to reproduce the error
Input `55`
hit `*`
input `5`
hit `=`
hit `-`
input `9`
watch the calculator spin away and return `9-`

## (Optinal) Browser and OS information
Tested on iOS safari and OSX chrome

**Comment by andersevenrud** [comment]
There's even more issues with it. I have to rewrite this app somewhat

**Comment by mcky** [comment]
![calc](https://cloud.githubusercontent.com/assets/2717635/17172548/894a31cc-53ed-11e6-8135-cf3099e7f3c4.gif)

**Comment by mcky** [comment]
Was gonna open one for the keyboard showing too - should I put that in a separate issue?

**Comment by andersevenrud** [comment]
"keyboard showing" ?

**Comment by andersevenrud** [comment]
Oh, on touch devices. That can apparently be solved by adding a `readonly="readonly"` attribute

**Comment by mcky** [comment]
https://github.com/os-js/OS.js/issues/456

**Comment by plungedtoilet** [comment]
can't do decimals

**Comment by plungedtoilet** [comment]
input `5`
click `,`
input `5`
click `=`

**Comment by andersevenrud** [comment]
@plungedtoilet Decimals should be working now

**Comment by marktopper** [comment]
I have made a fix for most of those calculator issues at #489.

However, is the issue with the keyboard on touch devices still a problem @mcky?
